baseURL = "https://amatsukiurato.github.io"
title = "ぎじゅつわふたー"
author = "Amatsuki"
enableGitInfo = true
canonifyurls = true
paginate = 4
languageCode = "ja-jp"
theme = "hugo-blog-jeffprod"
pygmentsUseClasses = true
pygmentsCodefences = true
hasCJKLanguage = true
summaryLength = 250
disqusShortname = "https-amatsukiurato-github-io"
enableEmoji = true


[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

[params]
    twitter = "https://twitter.com/AmatsukiUrato"
    github = "https://github.com/AmatsukiUrato"

[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = true