baseURL = "https://amatsukiurato.github.io"
title = "Amatsukiメモ"
author = "Amatsuki"
canonifyurls = true
paginate = 4
languageCode = "ja-jp"
theme = "hugo-blog-jeffprod"
pygmentsUseClasses = true
pygmentsCodefences = true
enableGitInfo = true

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

[params]
    twitter = "https://twitter.com/AmatsukiUrato"
    github = "https://github.com/AmatsukiUrato"