baseURL = "https://master.d1amwzw2qgb3d2.amplifyapp.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "m10c"


[[params.social]]
  name = "github"
  url = "https://github.com/vaga"

[params.style]
darkestColor = "#d35050"
darkColor = "#212121"
lightColor = "#f5e3e0"
lightestColor = "#f5f5f5"
primaryColor = "#fff"