languageCode = "ja-jp"
title = "天月メモ"
theme = "hugo-paper"
baseURL = "https://amatsukiurato.github.io/"
enableGitInfo = true

#[author]
#  name = "Amatsuki"
#  homepage = "https://AmatsukiUrato.github.io"
#
#
#[[params.social]]
#  name = "github"
#  url = "https://github.com/AmatsukiUrato"
#
#[[params.social]]
#  name = "twitter"
#  url = "https://twitter.com/AmatsukiUrato"
#
#[params.style]
#  darkestColor = "#d35050"
#  darkColor = "#212121"
#  lightColor = "#f5e3e0"
#  lightestColor = "#f5f5f5"
#  primaryColor = "#fff"
